as_subdirectory:
  can_cross_compile: true
  git_repo:
    repo_url: git@github.com:catchorg/Catch2.git
  namespace_config:
    cmakelists_linking: "Catch2::"

  mutually_exclusive:
    - Catch2WithMain, Catch2

  target_configs:
    Catch2WithMain: { }
    Catch2: { }
