as_subdirectory:
  can_cross_compile: true
  links:
    github: https://github.com/catchorg/Catch2

  download_info:
    git_method:
      repo_url: git@github.com:catchorg/Catch2.git

  namespace_config:
    cmakelists_linking: "Catch2::"

  mutually_exclusive:
    - [ with_main, without_main ]

  target_configs:
    with_main:
      actual_target_name: Catch2WithMain
    without_main:
      actual_target_name: Catch2
