as_subdirectory:
  can_cross_compile: false
  links:
    github: https://github.com/CrowCpp/Crow

  download_info:
    git_method:
      repo_url: git@github.com:CrowCpp/Crow.git

  namespace_config:
    cmakelists_linking: "Crow::"
  
  # TODO: Implement features for predefined dependencies.
  # feature_mode:
  #   list_var: CROW_FEATURES

  # features:
  #   ssl:
  #     default: false
  #   compression:
  #     default: false

  target_configs:
    crow:
      actual_target_name: Crow
      external_requires:
        - asio::asio
        - openssl::ssl
        - zlib::zlib
        # - (( feature:ssl )) openssl::ssl
        # - (( feature:compression )) zlib::zlib
