cmake_module:
  module_type: CustomFindModule
  found_var: Brotli_FOUND

  links:
    gcmake_readme: "https://github.com/scupit/gcmake-dependency-configs/tree/develop/brotli"

  debian_packages:
    runtime:
      - libbrotli1
    dev:
      - libbrotli-dev

  namespace_config:
    cmakelists_linking: "Brotli::"
  
  targets:
    encoder:
      actual_target_name: brotlienc
    decoder:
      actual_target_name: brotlidec
    common:
      actual_target_name: brotlicommon