as_subdirectory:
  can_cross_compile: true

  links:
    github: https://github.com/raysan5/raylib

  download_info:
    git_method:
      repo_url: git@github.com:raysan5/raylib.git
    url_method:
      url_base: https://github.com/raysan5/raylib/archive/refs/tags/
      version_transform: "{{MAJOR}}.{{MINOR}}.{{PATCH}}"
      extensions:
        windows: zip
        unix: tar.gz

  namespace_config:
    cmakelists_linking: ""

  # TODO: When compiling with Emscripten, raylib requires the '-sASYNCIFY' flag
  # to be used when linking. However, the 'raylib' target doesn't pass that flag
  # to dependent targets. For now, it's fine to leave it since GCMake now uses '-sASYNCIFY'
  # by default. In the future, I might create a '_raylib_compat' target which passes flags
  # like this on to dependent targets.
  target_configs:
    raylib:
      external_requires:
        - glfw::glfw
        - opengl::opengl
