as_subdirectory:
  can_cross_compile: true
  links:
    github: https://github.com/Neargye/magic_enum/blob/master/CMakeLists.txt

  download_info:
    git_method:
      repo_url: git@github.com:Neargye/magic_enum.git

  namespace_config:
    cmakelists_linking: "magic_enum::"

  install_var: MAGIC_ENUM_OPT_INSTALL
  target_configs:
    magic_enum: { }
