cmake_module:
  module_type: ConfigFile
  module_name: SDL2
  found_var: SDL2_FOUND

  # Additional vars:
  # SDL2_SDL2_FOUND
  # SDL2_SDL2-static_FOUND
  # SDL2_SDL2main_FOUND
  # SDL2_SDL2test_FOUND
  # SDL2_BINDIR

  links:
    gcmake_readme: "https://github.com/scupit/gcmake-dependency-configs/tree/develop/sdl2"
    cmake_find_module: "https://cmake.org/cmake/help/latest/module/FindSDL.html"

  namespace_config:
    cmakelists_linking: "SDL2::"

  debian_packages:
    runtime:
      - libsdl2-2.0-0
    dev:
      - libsdl2-dev

  emscripten_config:
    link_flag: "-sUSE_SDL=2"

  mutually_exclusive:
    - [ sdl2, static ]
  
  targets:
    # Shared version of SDL2, if a shared SDL2 lib was found.
    # Otherwise acts as an alias to SDL2-static (see below).
    sdl2:
      actual_target_name: SDL2
    # Static version of SDL2
    static:
      actual_target_name: SDL2-static
    # Provides SDL_main. Always static.
    main:
      actual_target_name: SDL2main
      requires:
        - sdl2 or static     
    # Provides some common SDL testing functionality. Always static.
    test:
      actual_target_name: SDL2test
