cmake_module:
  module_type: ConfigFile
  found_var: SDL2_FOUND

  # Additional vars:
  # SDL2_SDL2_FOUND
  # SDL2_SDL2-static_FOUND
  # SDL2_SDL2main_FOUND
  # SDL2_SDL2test_FOUND
  # SDL2_BINDIR

  links:
    gcmake_readme: "https://github.com/scupit/gcmake-dependency-configs/tree/develop/SDL2"
    cmake_find_module: "https://cmake.org/cmake/help/latest/module/FindSDL.html"

  namespace_config:
    cmakelists_linking: "SDL2::"

  emscripten_config:
    link_flag: "-sUSE_SDL=2"

  mutually_exclusive:
    - [ SDL2, SDL2-static ]
  
  targets:
    # Shared version of SDL2, if a shared SDL2 lib was found.
    # Otherwise acts as an alias to SDL2-static (see below).
    SDL2: { }
    # Static version of SDL2
    SDL2-static: { }
    # Provides SDL_main. Always static.
    SDL2main:
      requires:
        - SDL2 or SDL2-static     
    # Provides some common SDL testing functionality. Always static.
    SDL2test: { }
