cmake_components_module:
  module_type: FindModule

  links:
    installation:
      prebuilt_downloads: "https://www.wxwidgets.org/downloads/"
      building: "https://docs.wxwidgets.org/trunk/overview_install.html"
    components_doc: "https://docs.wxwidgets.org/trunk/page_libs.html"
    cmake_find_module: "https://cmake.org/cmake/help/latest/module/FindwxWidgets.html"

  cmakelists_usage:
    link_format: Variable
    link_value: wxWidgets_LIBRARIES
    found_var: wxWidgets_FOUND

  # TODO: Make components a map of name to configuration, so that dependencies between
  # component 'targets' can be automatically established and other configuration can be
  # added in the future.
  components:
    aui:
      requires: [ core ]
    base: ~
    core:
      requires: [ base ]
    gl:
      requires: [ core ]
    html:
      requires: [ core ]
    media:
      requires: [ core ]
    net:
      requires: [ base ]
    propertygrid:
      requires: [ core ]
    qa:
      requires: [ xml, core ]
    ribbon:
      requires: [ core ]
    richtext:
      requires: [ html, xml ]
    stc:
      requires: [ core ]
    webview:
      requires: [ core ]
    xml:
      requires: [ base ]
    xrc:
      requires: [ core, html, xml ]
    