if( NOT "${_OPENSSL_PREVIOUSLY_SEARCHED_FOR_STATIC}" STREQUAL "${OPENSSL_USE_STATIC_LIBS}" )
  set( _OPENSSL_TYPE_SEARCHING_FOR_HAS_CHANGED TRUE )
else()
  set( _OPENSSL_TYPE_SEARCHING_FOR_HAS_CHANGED FALSE )
endif()

set( _OPENSSL_PREVIOUSLY_SEARCHED_FOR_STATIC ${OPENSSL_USE_STATIC_LIBS} CACHE INTERNAL "" FORCE )

# Redo the search (by clearing the search cache results) if the given hints might result in
# a different library being found.
if( OPENSSL_ROOT_DIR OR _OPENSSL_TYPE_SEARCHING_FOR_HAS_CHANGED )
  unset( OPENSSL_INCLUDE_DIR CACHE )
  unset( LIB_EAY CACHE )
  unset( LIB_EAY_DEBUG CACHE )
  unset( LIB_EAY_RELEASE CACHE )
  unset( SSL_EAY CACHE )
  unset( SSL_EAY_DEBUG CACHE )
  unset( SSL_EAY_RELEASE CACHE )
  unset( OPENSSL_SSL_LIBRARY CACHE )
  unset( OPENSSL_CRYPTO_LIBRARY CACHE )
endif()

set( _INITIAL_MODULE_PATH ${CMAKE_MODULE_PATH} )
set( CMAKE_MODULE_PATH )
include( FindOpenSSL )
set( CMAKE_MODULE_PATH ${_INITIAL_MODULE_PATH} )
