cmake_module:
  module_type: FindModule
  found_var: GLEW_FOUND

  links:
    installation:
      prebuilt_downloads: "http://glew.sourceforge.net/index.html"
      building: "http://glew.sourceforge.net/build.html"
    cmake_find_module: "https://cmake.org/cmake/help/latest/module/FindGLEW.html"

  namespace_config:
    cmakelists_linking: "GLEW::"
  
  mutually_exclusive:
    - glew, glew_s, GLEW
  
  targets:
    # TODO: Currently the target name 'key' is used as a link target in cmake_data.yaml AND
    # also used as the written target name when namespacing/writing the target to CMakeLists.txt.
    # That is fine. However, for situations like this where target names are weird or aren't clear,
    # I'd like to be able to change the written name of a target. That way the target name used in
    # cmake_data.yaml wouldn't need to change even if the library target did, and we can make usable
    # target names clearer.
    # For example, we could do this:
    # glew_shared:
    #   real_name: glew
    # glew_static:
    #   real_name: glew_s
    # GLEW: { }
    glew: { }    # Shared
    glew_s: { }  # Static
    GLEW: { }    # Either shared or static
