cmake_module:
  module_type: FindModule
  found_var: GLEW_FOUND

  links:
    installation:
      prebuilt_downloads: "http://glew.sourceforge.net/index.html"
      building: "http://glew.sourceforge.net/build.html"
    cmake_find_module: "https://cmake.org/cmake/help/latest/module/FindGLEW.html"

  namespace_config:
    cmakelists_linking: "GLEW::"
  
  targets:
    glew: { }     # Shared
    glew_s: { }  # Static
    GLEW: { }    # Either shared or static
