cmake_module:
  module_type: FindModule
  found_var: GLEW_FOUND

  links:
    installation:
      prebuilt_downloads: "https://glew.sourceforge.net/index.html"
      building: "https://glew.sourceforge.net/build.html"
    cmake_find_module: "https://cmake.org/cmake/help/latest/module/FindGLEW.html"

  namespace_config:
    cmakelists_linking: "GLEW::"
  
  mutually_exclusive:
    - [ glew-shared, glew-static, GLEW ]
  
  targets:
    glew-shared:
      actual_target_name: glew
    glew-static:
      actual_target_name: glew_s
    GLEW: { }    # Either shared or static
