cmake_module:
  module_type: BuiltinFindModule
  found_var: GLEW_FOUND

  links:
    gcmake_readme: "https://github.com/scupit/gcmake-dependency-configs/tree/develop/GLEW"
    cmake_find_module: "https://cmake.org/cmake/help/latest/module/FindGLEW.html"

  namespace_config:
    cmakelists_linking: "GLEW::"
  
  mutually_exclusive:
    - [ glew-shared, glew-static, GLEW ]
  
  targets:
    glew-shared:
      actual_target_name: glew
    glew-static:
      actual_target_name: glew_s
    GLEW: { }    # Either shared or static
