cmake_module:
  # CMake has a built-in FindGLEW.cmake file, but it doesn't seem to find glew even after
  # 'apt installing' both libglew2.1 and libglew-dev.
  module_type: ConfigFile
  module_name: GLEW
  found_var: GLEW_FOUND

  links:
    gcmake_readme: "https://github.com/scupit/gcmake-dependency-configs/tree/develop/GLEW"
    cmake_find_module: "https://cmake.org/cmake/help/latest/module/FindGLEW.html"

  namespace_config:
    cmakelists_linking: "GLEW::"
  
  mutually_exclusive:
    - [ shared, static, glew ]
  
  debian_packages:
    runtime:
      - libglew2.1
  
  targets:
    shared:
      actual_target_name: glew
      external_requires:
        - opengl::opengl
    static:
      actual_target_name: glew_s
      external_requires:
        - opengl::opengl
    glew: # Either shared or static
      actual_target_name: GLEW    
      external_requires:
        - opengl::opengl
