as_subdirectory:
  can_cross_compile: true
  links:
    github: https://github.com/jbeder/yaml-cpp

  download_info:
    git_method:
      repo_url: git@github.com:jbeder/yaml-cpp.git

  namespace_config:
    cmakelists_linking: "yaml-cpp::"

  install_var: YAML_CPP_INSTALL
  target_configs:
    yaml-cpp: { }