set( YAML_CPP_INSTALL ON CACHE BOOL "Whether to install yaml-cpp. GCMake sets this to ON by default." )
set( YAML_CPP_BUILD_TESTS OFF CACHE BOOL "Whether to build yaml-cpp tests. GCMake sets this to OFF by default." )
set( YAML_CPP_BUILD_CONTRIB OFF CACHE BOOL "Enable yaml-cpp contrib in librar. GCMake sets this to OFF by default." )
set( YAML_CPP_FORMAT_SOURCE OFF CACHE BOOL "Whether to format yaml-cpp files on configure. GCMake sets this to OFF by default." )
set( YAML_CPP_BUILD_TOOLS OFF CACHE BOOL "Whether to build yaml-cpp utility executables. GCMake sets this to OFF by default." )