as_subdirectory:
  can_cross_compile: true
  links:
    github: https://github.com/google/googletest

  download_info:
    git_method:
      repo_url: git@github.com:google/googletest.git

  namespace_config:
    cmakelists_linking: "GTest::"

  mutually_exclusive:
    - [ with_main, without_main ]

  install_var: INSTALL_GTEST
  install_by_default: false

  target_configs:
    without_main:
      actual_target_name: gtest
    with_main:
      actual_target_name: gtest_main
