as_subdirectory:
  can_cross_compile: true
  git_repo:
    repo_url: git@github.com:google/googletest.git
  namespace_config:
    cmakelists_linking: "GTest::"

  mutually_exclusive:
    - [ gtest, gtest_main ]

  install_var: INSTALL_GTEST
  install_by_default: false

  target_configs:
    gtest: { }
    gtest_main: { }
