as_subdirectory:
  can_cross_compile: true
  requires_custom_fetchcontent_populate: true

  links: 
    github: https://github.com/ocornut/imgui
  git_repo:
    repo_url: git@github.com:ocornut/imgui.git
  namespace_config:
    cmakelists_linking: "imgui::"

  # TODO: Add the FreeType extension https://github.com/ocornut/imgui/tree/master/misc/freetype
  # and make it depend on FreeType once a predefined dependency is added for FreeType 
  # using https://cmake.org/cmake/help/latest/module/FindFreetype.html
  target_configs:
    imgui_core: { }

    ((android)) android_opengl2:
      requires: [ imgui_core ]
    ((android)) android_opengl3:
      requires: [ imgui_core ]

    # TODO: Add these external_requires once implementd.
    glfw_opengl2:
      requires: [ imgui_core ]
      # external_requires: [ GLFW::glfw ]
    glfw_opengl3:
      requires: [ imgui_core ]
      # external_requires: [ GLFW::glfw ]
    glfw_vulkan:
      requires: [ imgui_core ]
      # external_requires: [ GLFW::glfw ]

    sdl_opengl2:
      requires: [ imgui_core ]
      # external_requires: [ SDL2::SDL2 or SDL2::SDL2-static ]
    sdl_opengl3:
      requires: [ imgui_core ]
      # external_requires: [ SDL2::SDL2 or SDL2::SDL2-static ]
    sdl_vulkan:
      requires: [ imgui_core ]
      # external_requires: [ SDL2::SDL2 or SDL2::SDL2-static ]
    ((windows)) sdl_directx9:
      requires: [ imgui_core ]
      # external_requires: [ SDL2::SDL2 or SDL2::SDL2-static ]
    ((windows)) sdl_directx10:
      requires: [ imgui_core ]
      # external_requires: [ SDL2::SDL2 or SDL2::SDL2-static ]
    ((windows)) sdl_directx11:
      requires: [ imgui_core ]
      # external_requires: [ SDL2::SDL2 or SDL2::SDL2-static ]
    ((windows)) sdl_directx12:
      requires: [ imgui_core ]
      # external_requires: [ SDL2::SDL2 or SDL2::SDL2-static ]
    sdl_sdlrenderer:
      requires: [ imgui_core ]
      # external_requires: [ SDL2::SDL2 or SDL2::SDL2-static ]

    ((windows)) win32_directx9:
      requires: [ imgui_core ]
    ((windows)) win32_directx10:
      requires: [ imgui_core ]
    ((windows)) win32_directx11:
      requires: [ imgui_core ]
    ((windows)) win32_directx12:
      requires: [ imgui_core ]