as_subdirectory:
  can_cross_compile: true
  requires_custom_fetchcontent_populate: true

  links: 
    github: https://github.com/ocornut/imgui

  download_info:
    git_method:
      repo_url: git@github.com:ocornut/imgui.git
    url_method:
      url_base: https://github.com/ocornut/imgui/archive/refs/tags/
      version_transform: "v{{MAJOR}}.{{MINOR}}"
      extensions:
        windows: zip
        unix: tar.gz

  namespace_config:
    cmakelists_linking: "imgui::"

  # TODO: Add individual implementations, not just the supported combinations. Developers should still
  # be able to write their own backend while using a base implementation.
  target_configs:
    core:
      actual_target_name: imgui_core
    freetype_extension:
      actual_target_name: imgui_freetype_extension
      requires:
        - core
      external_requires:
        - freetype::freetype

    ((android)) android_opengl2:
      requires:
        - core
      external_requires:
        - opengl::opengl
    ((android)) android_opengl3:
      requires:
        - core
      external_requires:
        - opengl::opengl

    glfw_opengl2:
      requires:
        - core
      external_requires:
        - glfw::glfw
        - opengl::opengl
    glfw_opengl3:
      requires:
        - core
      external_requires:
        - glfw::glfw
        - opengl::opengl

    # TODO: Add this back once Vulkan is added as a predefined dependency
    # glfw_vulkan:
    #   requires: [ core ]
    #   external_requires:
    #     - GLFW::GLFW
    #     - Vulkan::Vulkan

    sdl_opengl2:
      requires:
        - core
      external_requires:
        - sdl2::sdl2 or sdl2::static
        - opengl::opengl
    sdl_opengl3:
      requires:
        - core
      external_requires:
        - sdl2::sdl2 or sdl2::static
        - opengl::opengl
    # TODO: Add this back once Vulkan is added as a predefined dependency
    # sdl_vulkan:
    #   requires: [ core ]
    #   external_requires:
    #     - SDL2::SDL2 or SDL2::static
    #     - Vulkan::Vulkan
    ((windows)) sdl_directx9:
      requires:
        - core
      external_requires:
        - sdl2::sdl2 or sdl2::static
    ((windows)) sdl_directx10:
      requires:
        - core
      external_requires:
        - sdl2::sdl2 or sdl2::static
    ((windows)) sdl_directx11:
      requires:
        - core
      external_requires:
        - sdl2::sdl2 or sdl2::static
    ((windows)) sdl_directx12:
      requires:
        - core
      external_requires:
        - sdl2::sdl2 or sdl2::static
    sdl_sdlrenderer:
      requires:
        - core
      external_requires:
        - sdl2::sdl2 or sdl2::static

    ((windows)) win32_directx9:
      requires: [ core ]
    ((windows)) win32_directx10:
      requires: [ core ]
    ((windows)) win32_directx11:
      requires: [ core ]
    ((windows)) win32_directx12:
      requires: [ core ]