as_subdirectory:
  can_cross_compile: true
  requires_custom_fetchcontent_populate: true

  links: 
    github: https://github.com/nothings/stb

  download_info:
    git_method:
      repo_url: git@github.com:nothings/stb.git

  namespace_config:
    cmakelists_linking: "stb::"
  target_configs:
    image: { }
    image_write: { }
    image_resize: { }
    divide: { }
    # There are more. TODO: Add the rest here once they are added to the custom_populate.cmake