as_subdirectory:
  can_cross_compile: true
  links:
    github: https://github.com/fmtlib/fmt

  download_info:
    git_method:
      repo_url: git@github.com:fmtlib/fmt.git

  namespace_config:
    cmakelists_linking: "fmt::"
  
  install_var: FMT_INSTALL
  target_configs:
    fmt: { }