as_subdirectory:
  can_cross_compile: true
  git_repo:
    repo_url: git@github.com:fmtlib/fmt.git
  namespace_config:
    cmakelists_linking: "fmt::"
  
  install_var: FMT_INSTALL
  target_configs:
    fmt: { }