as_subdirectory:
  can_cross_compile: true
  links:
    github: https://github.com/ArthurSonzogni/FTXUI
  git_repo:
    repo_url: git@github.com:ArthurSonzogni/FTXUI.git
  namespace_config:
    cmakelists_linking: "ftxui::"

  install_var: FTXUI_ENABLE_INSTALL
  target_configs:
    screen: { }
    dom: { }
    component: { }
