as_subdirectory:
  can_cross_compile: true
  links:
    github: https://github.com/doctest/doctest

  download_info:
    git_method:
      repo_url: git@github.com:doctest/doctest.git

  namespace_config:
    cmakelists_linking: "doctest::"

  inverse_install_var: DOCTEST_NO_INSTALL
  install_by_default: false

  mutually_exclusive:
    - [ doctest, doctest_with_main ]

  target_configs:
    doctest: { }
    doctest_with_main: { }
