as_subdirectory:
  can_cross_compile: true
  git_repo:
    repo_url: git@github.com:doctest/doctest.git
  namespace_config:
    cmakelists_linking: "doctest::"

  mutually_exclusive:
    - [ doctest, doctest_with_main ]

  target_configs:
    doctest: { }
    doctest_with_main: { }
