as_subdirectory:
  can_cross_compile: true
  links:
    github: https://github.com/CLIUtils/CLI11

  download_info:
    git_method:
      repo_url: git@github.com:CLIUtils/CLI11.git

  namespace_config:
    cmakelists_linking: "CLI11::"

  target_configs:
    cli11:
      actual_target_name: CLI11
