as_subdirectory:
  # TODO: Might actually be able to trivially cross-compile glfw. Test first, then decide.
  can_cross_compile: false
  config_file_project_name: glfw3
  links:
    github: https://github.com/glfw/glfw

  download_info:
    git_method:
      repo_url: git@github.com:glfw/glfw.git

  namespace_config:
    cmakelists_linking: ""

  debian_packages:
    runtime:
      - libglfw3
    dev:
      - libglfw3-dev

  emscripten_config:
    link_flag: "-sUSE_GLFW=3"
    is_flag_link_time_only: true

  install_var: GLFW_INSTALL
  target_configs:
    glfw: { }
