as_subdirectory:
  # TODO: Might actually be able to trivially cross-compile glfw. Test first, then decide.
  can_cross_compile: false
  config_file_project_name: glfw3
  links:
    github: https://github.com/glfw/glfw
  git_repo:
    repo_url: git@github.com:glfw/glfw.git
  namespace_config:
    cmakelists_linking: ""

  emscripten_config:
    link_flag: "-USE_GLFW=3"

  install_var: GLFW_INSTALL
  target_configs:
    glfw: { }
