as_subdirectory:
  can_cross_compile: false
  config_file_project_name: glfw3
  git_repo:
    repo_url: git@github.com:glfw/glfw.git
  namespace_config:
    cmakelists_linking: ""

  install_var: GLFW_INSTALL
  target_configs:
    glfw: { }
