as_subdirectory:
  can_cross_compile: false
  links:
    github: https://github.com/SFML/SFML
  git_repo:
    repo_url: git@github.com:SFML/SFML.git
  namespace_config:
    cmakelists_linking: sfml-
  target_configs:
    system: { }
    window:
      requires: [ system ]
    network:
      requires: [ system ]
    graphics:
      requires: [ window, system ]
    audio:
      requires: [ system ]
    ((windows)) main:
      requires: [ system ]