as_subdirectory:
  can_cross_compile: false
  links:
    github: https://github.com/SFML/SFML

  download_info:
    git_method:
      repo_url: git@github.com:SFML/SFML.git
    url_method:
      url_base: https://github.com/SFML/SFML/archive/refs/tags/
      version_transform: "{{MAJOR}}.{{MINOR}}.{{PATCH}}"
      extensions:
        windows: zip
        unix: tar.gz
  
  debian_packages:
    runtime:
      - libsfml-graphics2.5
      - libsfml-network2.5
      - libsfml-system2.5
      - libsfml-window2.5
      - libopenal1
      - libvorbis0a
      - libvorbisenc2
      - libvorbisfile3
      - libflac8
      - libfreetype6
      - libx11-6
      - libxrandr2
      - libudev1
      - libopengl0
      - libogg0
    dev:
      - libsfml-dev
      - libopenal-dev
      - libvorbis-dev
      - libflac-dev
      - libfreetype6-dev
      - libx11-dev
      - libxrandr-dev
      - libudev-dev
      - libopengl-dev
      - libogg-dev

  namespace_config:
    cmakelists_linking: sfml-

  target_configs:
    system: { }
    window:
      requires: [ system ]
    network:
      requires: [ system ]
    graphics:
      requires: [ window, system ]
    audio:
      requires: [ system ]
    ((windows)) main:
      requires: [ system ]