as_subdirectory:
  can_cross_compile: false
  links:
    github: https://github.com/SFML/SFML

  download_info:
    git_method:
      repo_url: git@github.com:SFML/SFML.git
    url_method:
      url_base: https://github.com/SFML/SFML/archive/refs/tags/
      version_transform: "{{MAJOR}}.{{MINOR}}.{{PATCH}}"
      extensions:
        windows: zip
        unix: tar.gz

  namespace_config:
    cmakelists_linking: sfml-

  target_configs:
    system: { }
    window:
      requires: [ system ]
    network:
      requires: [ system ]
    graphics:
      requires: [ window, system ]
    audio:
      requires: [ system ]
    ((windows)) main:
      requires: [ system ]