as_subdirectory:
  git_repo:
    repo_url: git@github.com:SFML/SFML.git
  namespace_config:
    cmakelists_linking: sfml-
  target_names:
    system: ~
    window:
      requires: [ system ]
    network:
      requires: [ system ]
    graphics:
      requires: [ window, system ]
    audio:
      requires: [ system ]
    # sfml-main is only available when building for windows
    # TODO: System for platform-specific dependencies
    # Also, I'm not sure yet if this requires 'system' or not.
    main: ~