as_subdirectory:
  can_cross_compile: true
  links:
    github: https://github.com/jarro2783/cxxopts

  download_info:
    git_method:
      repo_url: git@github.com:jarro2783/cxxopts.git

  namespace_config:
    cmakelists_linking: "cxxopts::"

  install_var: CXXOPTS_ENABLE_INSTALL
  target_configs:
    cxxopts: { }
