as_subdirectory:
  can_cross_compile: true

  download_info:
    git_method:
      # GLM currently conflicts with GLFW because both projects create an 'uninstall' target, but only GLFW
      # creates it conditionally. I'll submit a bug report and a pull request to GLM. Use the master branch of my fork
      # until that goes through.
      # repo_url: git@github.com:g-truc/glm.git
      repo_url: git@github.com:scupit/glm.git

  namespace_config:
    cmakelists_linking: "glm::"

  install_var: GLM_BUILD_INSTALL
  target_configs:
    glm: { }
