as_subdirectory:
  can_cross_compile: true

  # TODO: I need to make a PR to the glm repo with the installation variable addition.
  # once that is merged, add the GML GitHub link here.
  download_info:
    git_method:
      # repo_url: git@github.com:g-truc/glm.git
      repo_url: git@github.com:scupit/glm.git

  namespace_config:
    cmakelists_linking: "glm::"

  install_var: GLM_INSTALL
  target_configs:
    glm: { }