as_subdirectory:
  can_cross_compile: true
  git_repo:
    # repo_url: git@github.com:g-truc/glm.git
    repo_url: git@github.com:scupit/glm.git
  namespace_config:
    cmakelists_linking: "glm::"

  install_var: GLM_INSTALL
  target_configs:
    glm: { }