as_subdirectory:
  can_cross_compile: true

  download_info:
    git_method:
      # GLM currently conflicts with GLFW because both projects create an 'uninstall' target, but only GLFW
      # creates it conditionally. I'll submit a bug report and a pull request to GLM. Use the master branch of my fork
      # until that goes through.
      # repo_url: git@github.com:g-truc/glm.git
      repo_url: git@github.com:scupit/glm.git

  namespace_config:
    cmakelists_linking: "glm::"

  install_var: GLM_BUILD_INSTALL
  target_configs:
    # If GLM_BUILD_LIBRARY is ON, 'glm' will be a compiled library. Otherwise,
    # it's the header_only library. We set GLM_BUILD_LIBRARY to ON by default
    # in pre_load.cmake. 
    glm:
      requires: [ _private_header_only ]

    # Needed for when we install the compiled library. Not sure why this isn't
    # happening in GLM itself.
    _private_header_only:
      actual_target_name: glm-header-only
