as_subdirectory:
  can_cross_compile: true
  requires_custom_fetchcontent_populate: true

  download_info:
    url_method:
      url_base_by_version:
        # The sqlite3 amalgamation release URL changes by year, which is annoying.
        "3.41.0": https://www.sqlite.org/2023/sqlite-amalgamation- 
        "3.37.2": https://www.sqlite.org/2022/sqlite-amalgamation- 
        "3.34.1": https://www.sqlite.org/2021/sqlite-amalgamation- 
      version_transform: "{{MAJOR}}{{MINOR:3}}{{PATCH:3}}"
      extensions:
        windows: zip
        unix: tar.gz

  debian_packages:
    runtime:
      - libsqlite3-0
    dev:
      - libsqlite3-dev

  emscripten_config:
    link_flag: "-sUSE_SQLITE3=1"

  namespace_config:
    cmakelists_linking: "sqlite3::"

  target_configs:
    sqlite3: { }
