as_subdirectory:
  git_repo:
    repo_url: git@github.com:ArthurSonzogni/nlohmann_json_cmake_fetchcontent.git
  namespace_config:
    cmakelists_linking: "nlohmann_json::"
  target_names:
    - nlohmann_json