as_subdirectory:
  installed_include_dir_name: nlohmann
  git_repo:
    recursive_clone: false
    repo_url: git@github.com:nlohmann/json.git
  namespace_config:
    cmakelists_linking: "nlohmann_json::"
  target_names:
    nlohmann_json: ~