as_subdirectory:
  can_cross_compile: true
  installed_include_dir_name: nlohmann
  links:
    github: https://github.com/nlohmann/json
  
  download_info:
    url_method:
      url_base: https://github.com/nlohmann/json/archive/refs/tags/
      version_transform: "v{{MAJOR}}.{{MINOR}}.{{PATCH}}"
      extensions:
        windows: zip
        unix: tar.gz
    git_method:
      repo_url: git@github.com:nlohmann/json.git
    
  namespace_config:
    cmakelists_linking: "nlohmann_json::"

  install_var: JSON_Install
  target_configs:
    nlohmann_json: { }