if( NOT "${_ZLIB_PREVIOUSLY_SEARCHED_FOR_STATIC}" STREQUAL "${ZLIB_USE_STATIC_LIBS}" )
  set( _ZLIB_TYPE_SEARCHING_FOR_HAS_CHANGED TRUE )
else()
  set( _ZLIB_TYPE_SEARCHING_FOR_HAS_CHANGED FALSE )
endif()

set( _ZLIB_PREVIOUSLY_SEARCHED_FOR_STATIC ${ZLIB_USE_STATIC_LIBS} CACHE INTERNAL "" FORCE )

# Redo the search (by clearing the search cache results) if the given hints might result in
# a different library being found.
if( ZLIB_ROOT OR _ZLIB_TYPE_SEARCHING_FOR_HAS_CHANGED )
  unset( ZLIB_LIBRARY_RELEASE CACHE )
  unset( ZLIB_LIBRARY_DEBUG CACHE )
  unset( ZLIB_INCLUDE_DIR CACHE )
endif()

set( _INITIAL_MODULE_PATH ${CMAKE_MODULE_PATH} )
set( CMAKE_MODULE_PATH )
include( FindZLIB )
set( CMAKE_MODULE_PATH ${_INITIAL_MODULE_PATH} )