cmake_module:
  module_type: FindModule
  found_var: OPENGL_FOUND

  links:
    cmake_find_module: "https://cmake.org/cmake/help/latest/module/FindOpenGL.html"

  namespace_config:
    cmakelists_linking: "OpenGL::"

  emscripten_config: { }
  
  targets:
    GL: { }