cmake_builtin_find_module:
  # find_module_name: FindOpenGL

  # links:
  #   cmake_find_module: "https://cmake.org/cmake/help/latest/module/FindOpenGL.html"

  # cmakelists_usage:
  #   mode: Target
  #   value: OpenGL::GL