cmake_module:
  module_type: BuiltinFindModule
  module_name: OpenGL
  found_var: OPENGL_FOUND

  links:
    gcmake_readme: "https://github.com/scupit/gcmake-dependency-configs/tree/develop/OpenGL"
    cmake_find_module: "https://cmake.org/cmake/help/latest/module/FindOpenGL.html"

  namespace_config:
    cmakelists_linking: "OpenGL::"

  emscripten_config:
    is_internally_supported: true
  
  targets:
    opengl:
      actual_target_name: GL
    glu:
      actual_target_name: GLU